module Version where 
{-| This file must be auto-generated by a bash or Python script.
    Currently it is hard-coded by hand.

    Use the following git command to get version information: 
        git describe --tags --long
-}


version : String 
version = "v2.2-beta-0-g0fda8de"