#!/usr/bin/env python

# Inspired by 
# https://gitfu.wordpress.com/2008/05/25/git-describe-great-another-way-to-refer-to-commits/
# http://gitready.com/beginner/2009/02/03/tagging.html

#####################
## Get Version details
######################
import commands
status, version = commands.getstatusoutput ("git describe --tags --long")
if not status: 
	print ("Version: " + version)
else: 
	print "git describe return bad status!"
	version = "NA"
	# Need to exit gracefully
	# Now it continues!!! 

####################
## build elm code 
####################
fileContent = \
'''
module Version where \n\
{-| This file is auto-generated by the Python script version.py. -} \n\
\n\
\n\
version : String \n\
'''

fileContent = fileContent + 'version = "' + version + '"\n\n'

#print (fileContent)

##################
## Create file after backing up previous one, if it exists
##################
fo = open ("Version.elm", "w+")
#print "Name of file opened ", fo.name 

fo.write (fileContent)
fo.close()